### ISSUE TITLE
"npx nwlink" fails on last versions (I tried 0.0.17 to 0.0.12)

### ISSUE THREAD

**Issue by Naereen** [numworks/epsilon-sample-app-c#4]
Hi there,
Thanks for this interesting demo! I wanted to work on it. However...
I failed to compile it, on Ubuntu 22.04 Linux, using 
```bash
$ npx --version
8.5.1
$ node --version
v12.22.9
```

The compilation fails because in the Makefile, the `npx --yes -- nwlink@0.0.17` command is used, but it fails:
```bash
$ npx --yes -- nwlink@0.0.17
/home/USER/.npm/_npx/6d991536f923a4f6/node_modules/nwlink/dist/index.js:1
(()=>{var t={7481:(t,e,r)=>{var n,o=(n=(n="undefined"!=typeof document&&document.currentScript?document.currentScript.src:void 0)||__filename,function(t);

SyntaxError: Unexpected token '='
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/home/lilian/.npm/_npx/6d991536f923a4f6/node_modules/nwlink/bin/nwlink:2:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

I tried from versions 0.0.17 to 0.0.12, each giving the same issue.

Could you @Ecco, @EmilieNumworks (and other authors maybe) help me here, please?
Thanks and regards from France as well ;-)
@Naereen

**Comment by Naereen** [comment]
Apparently, this has been opened also on the epsilon-sample-app-cpp project: https://github.com/numworks/epsilon-sample-app-cpp/issues/29

**Comment by EmilieNumworks** [comment]
It should work with a more recent node version!

**Comment by Naereen** [comment]
Hi there @EmilieNumworks and thanks for taking the time to look into this issue.
I'll try it the most recent version when possible, I will let you know whether it works or not !
Kind regards, and in advance a Merry Chrismas!
